In [ ]:
#numpy is a library for working with arrays.
#  It also has functions for working in the domain of linear algebra, fourier transform, and matrices.
#  It is also a powerful N-dimensional array object.
#numpy is written in C and Python. It is a powerful library for numerical computing in Python. It is used for working with arrays, matrices, and linear algebra. It is also used for working with large datasets and for performing mathematical operations on them.
#numpy array is same as c array. It is a collection of items of the same type. It is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [1]:
import numpy as np

In [5]:
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
#2d and 3d arrays
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c)#tensor

In [7]:
#data type
d = np.array([1, 2, 3], dtype=np.float32)
print(d)

[1. 2. 3.]


In [ ]:
#np.arrange() - like range() but for arrays
e = np.arange(10)
print(e)


[0 1 2 3 4 5 6 7 8 9]


In [14]:
#with reshape
f = np.arange(1, 11).reshape(2, 5)
print(f)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
#np.ones() and np.zeros()
g = np.ones((2, 3))#use for neural networks to initialize weights 
print(g)
h = np.zeros((2, 3))#use for neural networks to initialize biases
print(h)
k=np.random.rand(2, 3)#random numbers between 0 and 1

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
#np.linspace() - like np.arrange() but returns evenly spaced numbers over a specified interval
l = np.linspace(0, 10, 25)#start, stop, number of samples
print(l)


[ 0.          0.41666667  0.83333333  1.25        1.66666667  2.08333333
  2.5         2.91666667  3.33333333  3.75        4.16666667  4.58333333
  5.          5.41666667  5.83333333  6.25        6.66666667  7.08333333
  7.5         7.91666667  8.33333333  8.75        9.16666667  9.58333333
 10.        ]


In [ ]:
#np.identity() - returns the identity of an object. This is an integer which is guaranteed to be unique and constant for this object during its lifetime. Two objects with non-overlapping lifetimes may have the same id() value.
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
a1=np.arange(10)
a2=np.arange(12,dtype=np.float32).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [6]:
#ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


1
2
3


In [7]:
#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [8]:
#size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [9]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float32
int64


In [11]:
#Changing the dtype
a4=a3.astype(np.float32)
print(a4)

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]


In [15]:
#array operations
a5=np.array([1, 2, 3])
a6=np.array([4, 5, 6])
#arthmetic operations
print(a5*5)
print(a5 **2) 

[ 5 10 15]
[1 4 9]


In [16]:
#relational
a2>1

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [17]:
#vectorized operations
#arthmetic
print(a5*a6)#for all operations, the arrays must have the same shape or be broadcastable to the same shape


[ 4 10 18]


In [30]:
#Array Function
a=np.random.rand(2, 3)
a=np.round(a*100)
b=np.random.rand(2, 3)
b=np.round(b*100)


In [20]:
#max/min/prod
print(a)
print(a.max())
print(a.min())
print(a.prod())
#row max
print(a.max(axis=0))
#column max
print(a.max(axis=1))

[[95. 47. 80.]
 [44. 45. 50.]]
95.0
44.0
35362800000.0
[95. 47. 80.]
[95. 50.]


In [22]:
#mean/median/std/var
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))


60.166666666666664
48.5
19.894862541760762
395.8055555555555


In [3]:
#log
a1=np.random.randint(1,10)
print(np.exp(a1))


20.085536923187668


In [32]:
print(np.dot(a, b.T))

[[2074. 3766.]
 [2695. 8558.]]


In [ ]:
#indexiing and slicing
