In [2]:
import numpy as np

Numpy vs python list

In [3]:
#speed 
#python list
a=[i for i in range(1000000)]
b=[i for i in range(1000000,2000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)
#numpy array
a=np.array(a)
b=np.array(b)
start=time.time()
c=a+b
print(time.time()-start)

0.17827391624450684
0.01880645751953125


In [5]:
#Memory
a=[i for i in range(1000000)]
import sys
print(sys.getsizeof(a))
a=np.array(a)
print(sys.getsizeof(a))


8448728
8000112


Advance Indexing

In [10]:
#Normal indexing
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0][0])
#Fancy indexing
print(a[[0,1,2],[0,1,2]])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[1 5 9]


In [15]:
#boolean indexing
a=np.random.randint(1,100,24).reshape(4,6)
print(a[a%2==0])

[ 4 98 72  4 70 22 24 24]


In [17]:
result = a[(a % 2 == 0) & (a > 50)]
print(result)

[98 72 70]


In [16]:
print(a%2==0 & a>50)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()