In [1]:
import numpy as np

In [4]:
#np.sort()
a=np.random.randint(1,100,15)
np.sort(a)

array([ 1,  9, 18, 23, 29, 30, 34, 36, 44, 45, 65, 72, 80, 93, 95])

In [5]:
b=np.random.randint(1,45,15).reshape(3,5)
print(b)
print(np.sort(b))
print(np.sort(b,axis=1))

[[ 4  5 35 12  3]
 [44 37 25 13  3]
 [ 2 26 21  8 38]]
[[ 3  4  5 12 35]
 [ 3 13 25 37 44]
 [ 2  8 21 26 38]]
[[ 3  4  5 12 35]
 [ 3 13 25 37 44]
 [ 2  8 21 26 38]]


In [8]:
#np.append
np.append(a,24)

array([17, 15, 46, 34, 35, 23, 76, 11, 37, 46,  1, 55, 13, 14, 71, 24])

In [9]:
#np.concatinate
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[41.        , 23.        , 24.        , 37.        , 28.        ,
         0.98364174],
       [33.        , 41.        , 44.        , 36.        , 24.        ,
         0.7130941 ],
       [ 5.        , 20.        , 17.        , 40.        , 31.        ,
         0.35680412]])

np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [10]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [13]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [15]:
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0).shape

array([[17, 15, 46, 34, 35, 23, 76, 11, 37, 46,  1, 55, 13, 14, 71]])

In [21]:
np.expand_dims(a,axis=1).shape

(15, 1)

np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [22]:
a

array([17, 15, 46, 34, 35, 23, 76, 11, 37, 46,  1, 55, 13, 14, 71])

In [23]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 6, 11, 14]),)

In [24]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([17, 15, 46, 34, 35, 23,  0, 11, 37, 46,  1,  0, 13, 14,  0])

In [25]:
np.where(a%2 == 0,0,a)

array([17, 15,  0,  0, 35, 23,  0, 11, 37,  0,  1, 55, 13,  0, 71])

np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [26]:
a

array([17, 15, 46, 34, 35, 23, 76, 11, 37, 46,  1, 55, 13, 14, 71])

In [27]:
np.argmax(a)


np.int64(6)

In [28]:
b

array([[41, 23, 24, 37, 28],
       [33, 41, 44, 36, 24],
       [ 5, 20, 17, 40, 31]])

In [29]:
np.argmax(b,axis=0)
np.argmax(b,axis=1)

array([0, 2, 3])

In [30]:
# np.argmin
np.argmin(a)

np.int64(10)

np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [31]:
a

array([17, 15, 46, 34, 35, 23, 76, 11, 37, 46,  1, 55, 13, 14, 71])

In [32]:
np.cumsum(a)

array([ 17,  32,  78, 112, 147, 170, 246, 257, 294, 340, 341, 396, 409,
       423, 494])

In [34]:
np.cumsum(b,axis=1)#row
np.cumsum(b,axis=0)

array([[ 41,  23,  24,  37,  28],
       [ 74,  64,  68,  73,  52],
       [ 79,  84,  85, 113,  83]])

In [35]:
#np.cumprod()
np.cumprod(a)

array([                  17,                  255,                11730,
                     398820,             13958700,            321050100,
                24399807600,         268397883600,        9930721693200,
            456813197887200,      456813197887200,    25124725883796000,
         326621436489348000,  4572700110850872000, -7379685456360017088])

Np.percentile
It is use to compute th nth percentile of given data

In [ ]:
np.percentile(a,0)#2nd parameter represent the percentile
np.percentile(a,70)


np.float64(44.19999999999999)

In [40]:
#np.histogram:It reprent the frequency of the data
a

array([17, 15, 46, 34, 35, 23, 76, 11, 37, 46,  1, 55, 13, 14, 71])

In [41]:
np.histogram(a,bins=[0,20,40,60])

(array([6, 4, 3]), array([ 0, 20, 40, 60]))

np.corrcoef
Return pearson product-moment correlation coefficent

In [44]:
salary=np.array([12000,15000,6000,100000,67000])
exp=np.array([1,2,1,5,4])
np.corrcoef(salary,exp)

array([[1.        , 0.98122613],
       [0.98122613, 1.        ]])

In [ ]:
#np.isin
item=[20,30,40,55]
a[np.isin(a,item)]

array([30])

In [8]:
#np.flip
np.flip(a)

array([44, 80,  9, 72, 29, 30,  1, 23, 36, 95, 65, 18, 93, 45, 34])

In [9]:
np.flip(b,axis=1)

array([[ 3, 12, 35,  5,  4],
       [ 3, 13, 25, 37, 44],
       [38,  8, 21, 26,  2]])

In [10]:
a

array([34, 45, 93, 18, 65, 95, 36, 23,  1, 30, 29, 72,  9, 80, 44])

In [ ]:
#np.put
np.put(a,[0,6],[93,89])#[index1,index2...],[replacedval1,replacedval2...]
a

array([93, 45, 93, 18, 65, 95, 89, 23,  1, 30, 29, 72,  9, 80, 44])

In [14]:
#np.delete()
a

array([93, 45, 93, 18, 65, 95, 89, 23,  1, 30, 29, 72,  9, 80, 44])

In [ ]:
np.delete(a,[0,2,4])#index of the cell that we want to delete

array([45, 18, 95, 89, 23,  1, 30, 29, 72,  9, 80, 44])

Set Function

In [17]:
n=np.array([1,2,3,4,5])
m=np.array([3,4,5,6])
#np.union1d
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6])

In [21]:
#np.intersection1d
np.intersect1d(m,n)
np.setdiff1d(m,n)
np.setxor1d(n,m)
np.in1d(m,3)

/tmp/ipykernel_29685/60472731.py:5: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,3)


array([ True, False, False, False])

In [22]:
a

array([93, 45, 93, 18, 65, 95, 89, 23,  1, 30, 29, 72,  9, 80, 44])

In [23]:
np.clip(a,a_min=10,a_max=50)

array([50, 45, 50, 18, 50, 50, 50, 23, 10, 30, 29, 50, 10, 50, 44])